### ISSUE TITLE
Attackedatyaw animation is too intense

### ISSUE THREAD

**Issue by williewillus** [unascribed-archive/Ascribe#1]
It also doesn't work intermittently.

I suspect this is due to some logic in vanilla setting the client player's attackedAtYaw to 0 (look in EntityPlayerSP, I believe it's there). Which causes thrashing when the packet arrives as well

**Comment by williewillus** [comment]
This is in SSP btw

**Comment by exaskye** [comment]
I noticed it not working intermittently as well, but only in 1.8.9. I never had issues in 1.7.10.

As for the animation, since it's not something I control, how intense it is isn't my decision. The mod just syncs the field for use by the vanilla renderer.

**Comment by unascribed** [comment]
I actually can't find a single place in 1.8.9 where vanilla sets the attackedAtYaw to the proper value... I'm checking 1.7.10 now to see if they changed anything.

**Comment by williewillus** [comment]
I meant "too intense" as in the field sync seems to be conflicting with vanilla setting it to 0

**Comment by williewillus** [comment]
@unascribed It's intermittently not working in 1.8 because you don't wrap your handler in a runnable and run it on the main thread.

`Minecraft.getMinecraft().addScheduledTask(() -> {Minecraft.getMinecraft.thePlayer.attackedAtYaw = yaw});` or something like that

**Comment by exaskye** [comment]
Oh, duh. I forgot about that, I don't do very much 1.8 modding.
